name: delivery_boy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.0
  flex_color_scheme: ^8.0.2
  flutter_custom_clippers: ^2.1.0
  shimmer_animation: ^2.1.0+1
  animated_bottom_navigation_bar: ^1.3.3
  animated_segmented_tab_control: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  toastification: ^2.0.0
  extended_image: ^9.0.7
  gap: ^3.0.1
  flutter_adaptive_scaffold: ^0.3.1
  #state and management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.21.2
  go_router: ^14.2.3
  shared_preferences: ^2.2.2
  #util
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  fpdart: ^1.1.0
  equatable: ^2.0.5
  file_picker: ^9.0.2
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.2.5
  get_it: ^8.0.2
  collection: ^1.18.0
  riverpod_annotation: ^2.3.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^11.0.0
  lottie: ^3.1.2
  country_code_picker: ^3.0.0
  open_filex: ^4.7.0
  flutter_staggered_grid_view: ^0.7.0
  grouped_list: ^6.0.0
  flutter_html: ^3.0.0-beta.2

  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.2.8
  timeago: ^3.6.1
  pull_to_refresh: ^2.0.0
  flutter_polyline_points: ^2.0.0
  location: ^8.0.0
  geocoding: ^3.0.0
  firebase_messaging: ^15.0.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.1.1
  # flutter_ringtone_player: ^4.0.0+3
  flutter_local_notifications: ^18.0.1
  slang: ^4.3.0
  slang_flutter: ^4.3.0
  timelines_plus: ^1.0.6
  buttons_tabbar: ^1.3.13
  flutter_swipe_action_cell: ^3.1.4
  pinput: ^5.0.0
  syncfusion_flutter_charts:
    git:
      url: https://github.com/Luvti/flutter-widgets
      path: packages/syncfusion_flutter_charts
      ref: 15e3c4a95e3cf2e2393755bf5aa11c0206ed6dea #flutter/3.24
  vector_graphics: any
  event_bus: ^2.0.0
  smooth_page_indicator: ^1.2.0+3
  modal_bottom_sheet: ^3.0.0
  flutter_parsed_text: ^2.2.1
  share_plus: ^10.0.0
  shared_preferences_tools: ^1.1.0
  automatic_animated_list: ^1.1.0
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_gen_runner: ^5.7.0
  # slang_build_runner: ^3.31.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icon/
    - assets/png/
    - assets/svg/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter_gen:
  output: lib/_core/strings/
  integrations:
    flutter_svg: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: TR
  main_locale: en
  arb_dir: lib/_core/l10n/lang
  output_dir: lib/_core/l10n/gen_
